### DISCUSSION TITLE
Cannot get rewriting to work

### DISCUSSION THREAD

**Discussion by runiq** [stalwartlabs/smtp-server#25] [Q&A] [answered]
I'm trying to get  started with stalwart-smtp and I'm running into problems with address rewriting.

In order to get my feet wet, I simply want to rewrite _all_ addresses to either `from@example.org` (sender) or `to@example.org` (receiver). These are the session bits of my config:

```toml
[session.rcpt]
relay = true

[session.from]
rewrite = [
  { if = "sender", matches = ".*", then = "from@example.org" }, 
  { else = false },
]

[session.to]
rewrite = [
  { if = "rcpt", matches = ".*", then = "to@example.org" }, 
  { else = false },
]
```

Whatever I do, the addresses are not being rewritten. Can anyone tell me what I'm doing wrong?
